FROM ubuntu:16.04
ADD Python-3.6.7.tgz  /tmp/
RUN echo "deb http://mirrors.ustc.edu.cn/ubuntu/ xenial main restricted universe multiverse" > /etc/apt/sources.list \
&& echo "deb http://mirrors.ustc.edu.cn/ubuntu/ xenial-security main restricted universe multiverse" >> /etc/apt/sources.list \
&& echo "deb http://mirrors.ustc.edu.cn/ubuntu/ xenial-updates main restricted universe multiverse" >> /etc/apt/sources.list \
&& echo "deb http://mirrors.ustc.edu.cn/ubuntu/ xenial-proposed main restricted universe multiverse" >> /etc/apt/sources.list \
&& echo "deb http://mirrors.ustc.edu.cn/ubuntu/ xenial-backports main restricted universe multiverse" >> /etc/apt/sources.list \
&& echo "deb-src http://mirrors.ustc.edu.cn/ubuntu/ xenial main restricted universe multiverse" >> /etc/apt/sources.list \
&& echo "deb-src http://mirrors.ustc.edu.cn/ubuntu/ xenial-security main restricted universe multiverse" >> /etc/apt/sources.list \
&& echo "deb-src http://mirrors.ustc.edu.cn/ubuntu/ xenial-updates main restricted universe multiverse" >> /etc/apt/sources.list \
&& echo "deb-src http://mirrors.ustc.edu.cn/ubuntu/ xenial-proposed main restricted universe multiverse" >> /etc/apt/sources.list \
&& echo "deb-src http://mirrors.ustc.edu.cn/ubuntu/ xenial-backports main restricted universe multiverse" >> /etc/apt/sources.list \
&& apt update \
&& apt install libmysqlclient-dev -y \
&& apt install gcc -y \
&& apt install make -y \
&& apt install zlib* -y \
&& apt install libXt* -y \
&& apt install -y libbz2-dev python3-dev libxml2-dev libffi-dev libssl-dev libxslt1-dev \
&& apt install netcat -y \
&& apt-get install -y libgl1-mesa-dev \
&& cd /tmp/Python-3.6.7 \
&& ./configure --prefix=/usr/local/  \
&& make \
&& make install \
&& apt-get install -y nodejs nodejs-legacy npm curl nginx \
&& npm config set registry https://registry.npm.taobao.org \
&& npm install n -g \
&& n stable \
&& rm -rf /usr/bin/node \
&& rm -rf /usr/bin/npm \
&& ln -s /usr/local/n/versions/node/12.13.0/bin/node /usr/bin/node \
&& ln -s /usr/local/n/versions/node/12.13.0/bin/npm /usr/bin/npm \
&& npm -v \