version: '3.1'

services:
  db:
    image: mysql:5.7
    restart: always
    container_name: db
    environment:
        MYSQL_ROOT_PASSWORD: kops
    volumes:
        - ./mysql/:/docker-entrypoint-initdb.d/
        - ./mysql/mysql.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf
#    ports:
#        - 3307:3306
  app:
    image: neverqaz/kops:v1
    restart: always
    depends_on:
       - db
    links:
       - db
    ports:
       - 80:8080
    volumes:
       - ./log/:/code/backend/log

